# Generated by Django 5.1.1 on 2024-10-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
