# Generated by Django 5.1.1 on 2024-11-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0003_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
