# Generated by Django 5.1.1 on 2024-11-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0004_alter_login_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cpf',
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=123456789, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
