# Generated by Django 5.1.1 on 2024-11-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0005_remove_register_cpf_register_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
